# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Python37\progs\!generator\full\generator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_verbs = QtWidgets.QWidget()
        self.tab_verbs.setObjectName("tab_verbs")
        self.verb_counter = QtWidgets.QSpinBox(self.tab_verbs)
        self.verb_counter.setGeometry(QtCore.QRect(250, 430, 42, 22))
        self.verb_counter.setMinimum(1)
        self.verb_counter.setMaximum(10)
        self.verb_counter.setObjectName("verb_counter")
        self.checkList = QtWidgets.QCheckBox(self.tab_verbs)
        self.checkList.setGeometry(QtCore.QRect(20, 280, 151, 17))
        self.checkList.setObjectName("checkList")
        self.label_3 = QtWidgets.QLabel(self.tab_verbs)
        self.label_3.setGeometry(QtCore.QRect(240, 410, 71, 16))
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_verbs)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 441, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(10, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkScand = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkScand.setObjectName("checkScand")
        self.gridLayout_2.addWidget(self.checkScand, 0, 1, 1, 1)
        self.checkJewish = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkJewish.setObjectName("checkJewish")
        self.gridLayout_2.addWidget(self.checkJewish, 1, 1, 1, 1)
        self.checkCommon = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkCommon.setObjectName("checkCommon")
        self.gridLayout_2.addWidget(self.checkCommon, 1, 0, 1, 1)
        self.checkGreece = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkGreece.setObjectName("checkGreece")
        self.gridLayout_2.addWidget(self.checkGreece, 2, 1, 1, 1)
        self.checkSlav = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkSlav.setObjectName("checkSlav")
        self.gridLayout_2.addWidget(self.checkSlav, 2, 0, 1, 1)
        self.checkElven = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkElven.setEnabled(False)
        self.checkElven.setObjectName("checkElven")
        self.gridLayout_2.addWidget(self.checkElven, 0, 0, 1, 1)
        self.BrouseButton = QtWidgets.QPushButton(self.tab_verbs)
        self.BrouseButton.setGeometry(QtCore.QRect(250, 280, 101, 23))
        self.BrouseButton.setObjectName("BrouseButton")
        self.label = QtWidgets.QLabel(self.tab_verbs)
        self.label.setGeometry(QtCore.QRect(20, 20, 391, 31))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.tab_verbs)
        self.listWidget.setGeometry(QtCore.QRect(10, 510, 441, 192))
        self.listWidget.setObjectName("listWidget")
        self.StartButton = QtWidgets.QPushButton(self.tab_verbs)
        self.StartButton.setGeometry(QtCore.QRect(200, 710, 75, 23))
        self.StartButton.setObjectName("StartButton")
        self.label_2 = QtWidgets.QLabel(self.tab_verbs)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 131, 20))
        self.label_2.setObjectName("label_2")
        self.try_counter = QtWidgets.QSpinBox(self.tab_verbs)
        self.try_counter.setGeometry(QtCore.QRect(50, 430, 42, 22))
        self.try_counter.setMinimum(1)
        self.try_counter.setObjectName("try_counter")
        self.label_6 = QtWidgets.QLabel(self.tab_verbs)
        self.label_6.setGeometry(QtCore.QRect(190, 470, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.tab_verbs)
        self.label_4.setGeometry(QtCore.QRect(40, 410, 81, 16))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_verbs)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 310, 441, 71))
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.SaveButton_1 = QtWidgets.QPushButton(self.tab_verbs)
        self.SaveButton_1.setGeometry(QtCore.QRect(310, 710, 131, 23))
        self.SaveButton_1.setObjectName("SaveButton_1")
        self.tabWidget.addTab(self.tab_verbs, "")
        self.tab_letters = QtWidgets.QWidget()
        self.tab_letters.setObjectName("tab_letters")
        self.label_5 = QtWidgets.QLabel(self.tab_letters)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tab_letters)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 391, 151))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_letters)
        self.label_8.setGeometry(QtCore.QRect(170, 240, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_letters)
        self.lineEdit.setGeometry(QtCore.QRect(30, 210, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(self.tab_letters)
        self.label_9.setGeometry(QtCore.QRect(310, 180, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_letters)
        self.label_10.setGeometry(QtCore.QRect(190, 330, 61, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.tab_letters)
        self.pushButton.setGeometry(QtCore.QRect(170, 610, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_letters)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 370, 441, 192))
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_letters)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 77, 25))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_letters)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 210, 171, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.try_counter_2 = QtWidgets.QSpinBox(self.tab_letters)
        self.try_counter_2.setGeometry(QtCore.QRect(200, 270, 42, 22))
        self.try_counter_2.setMinimum(1)
        self.try_counter_2.setObjectName("try_counter_2")
        self.SaveButton_2 = QtWidgets.QPushButton(self.tab_letters)
        self.SaveButton_2.setGeometry(QtCore.QRect(310, 610, 131, 23))
        self.SaveButton_2.setObjectName("SaveButton_2")
        self.tabWidget.addTab(self.tab_letters, "")
        self.tab_save = QtWidgets.QWidget()
        self.tab_save.setObjectName("tab_save")
        self.label_11 = QtWidgets.QLabel(self.tab_save)
        self.label_11.setGeometry(QtCore.QRect(160, 20, 141, 20))
        self.label_11.setObjectName("label_11")
        self.SaveButton_3 = QtWidgets.QPushButton(self.tab_save)
        self.SaveButton_3.setGeometry(QtCore.QRect(240, 630, 131, 23))
        self.SaveButton_3.setObjectName("SaveButton_3")
        self.CleanButton = QtWidgets.QPushButton(self.tab_save)
        self.CleanButton.setGeometry(QtCore.QRect(90, 630, 75, 23))
        self.CleanButton.setObjectName("CleanButton")
        self.Results = QtWidgets.QListWidget(self.tab_save)
        self.Results.setGeometry(QtCore.QRect(15, 60, 451, 511))
        self.Results.setObjectName("Results")
        self.tabWidget.addTab(self.tab_save, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkList.setText(_translate("MainWindow", "Ввести свой список имен"))
        self.label_3.setText(_translate("MainWindow", "Число слогов"))
        self.checkScand.setText(_translate("MainWindow", "Скандинавский"))
        self.checkJewish.setText(_translate("MainWindow", "Еврейский"))
        self.checkCommon.setText(_translate("MainWindow", "Всякоразный"))
        self.checkGreece.setText(_translate("MainWindow", "Греческий"))
        self.checkSlav.setText(_translate("MainWindow", "Славянский"))
        self.checkElven.setText(_translate("MainWindow", "Эльфийский"))
        self.BrouseButton.setText(_translate("MainWindow", "Открыть файл"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Генератор имен по заданному шаблону.</p></body></html>"))
        self.StartButton.setText(_translate("MainWindow", "Начать"))
        self.label_2.setText(_translate("MainWindow", "Тип имени"))
        self.label_6.setText(_translate("MainWindow", "результат"))
        self.label_4.setText(_translate("MainWindow", "Число попыток"))
        self.SaveButton_1.setText(_translate("MainWindow", "Сохранить результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_verbs), _translate("MainWindow", "Tab 1"))
        self.label_5.setText(_translate("MainWindow", "Имя"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Введите шаблон имени и фамилии. </p><p>Для случайно генерируемой буквы, поставьте звездочку (*), </p><p>для гласной буквы - 1, для согласной - 2; или введите требуемую букву.</p><p>Пример: 1*****ция.</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Число попыток"))
        self.label_9.setText(_translate("MainWindow", "Фамилия"))
        self.label_10.setText(_translate("MainWindow", "результат"))
        self.pushButton.setText(_translate("MainWindow", "Начать"))
        self.SaveButton_2.setText(_translate("MainWindow", "Сохранить результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_letters), _translate("MainWindow", "Tab 2"))
        self.label_11.setText(_translate("MainWindow", "Сохраненные результаты"))
        self.SaveButton_3.setText(_translate("MainWindow", "Сохранить в файл"))
        self.CleanButton.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_save), _translate("MainWindow", "Page"))
